### ISSUE TITLE
Beacon of Faith-Holy Paladin

### ISSUE THREAD

**Issue by Gal10** [Toludin/Healium#9] opened 2018-08-07 06:36 UTC
Doesnt show on player frame when I cast it :C

**Comment by Toludin** [comment] 2018-08-07 07:02
I can't reproduce this issue. Is this only when you cast it on someone else, besides yourself? A raid member perhaps? I tried it on myself in the party window and it showed up just fine (both Beacon of Light and Beacon of Faith). Any more info or screenshots would be helpful.

**Comment by Gal10** [comment] 2018-08-08 02:56
Heya,

When casting (on myself or someone else) Beacon of Light I see it on player
frame(on left side as usual) no problem. But when casting Beacon of Faith no
Icon is shown alongside player frame. Btw it should be seen when casting
outside raid or party too. 
 
 
 
 
-------Original Message-------
 
From: Toludin
Date: 08/07/18 10:03:02
To: Toludin/Healium
Cc: Gal10;  Author
Subject: Re: [Toludin/Healium] Beacon of Faith-Holy Paladin (#9)
 
I can't reproduce this issue. Is this only when you cast it on someone else,
besides yourself? A raid member perhaps? I tried it on myself in the party
window and it showed up just fine (both Beacon of Light and Beacon of Faith)
 Any more info or screenshots would be helpful.

**Comment by Gal10** [comment] 2018-08-08 06:52
All oki now. Ignore my request. 
 
 
 
 
-------Original Message-------
 
From: Toludin
Date: 08/07/18 10:03:02
To: Toludin/Healium
Cc: Gal10;  Author
Subject: Re: [Toludin/Healium] Beacon of Faith-Holy Paladin (#9)
 
I can't reproduce this issue. Is this only when you cast it on someone else,
besides yourself? A raid member perhaps? I tried it on myself in the party
window and it showed up just fine (both Beacon of Light and Beacon of Faith)
 Any more info or screenshots would be helpful.

**Comment by Toludin** [comment] 2018-08-08 09:15
Ok sounds good, I'll close this out.

**Closed by Toludin** 2018-08-08 09:15 UTC
